version: "3"

x-common-vars: &common-vars
  PG_USERNAME: postgres
  PG_PASSWORD: postgres
  PG_HOST: db
x-base-app-settings: &base-app-settings
  depends_on:
    - db
  image: human-essentials
  environment:
    <<: *common-vars
  networks:
    - human-essentials
  volumes:
    - .:/app

services:
  app:
    profiles:
      - build
    <<: *base-app-settings
    build: .
    command: echo Base image only for building
  web:
    <<: *base-app-settings
    ports:
      - "3000:3000"
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b 0.0.0.0"
  worker:
    <<: *base-app-settings
    command: bundle exec rails jobs:work
  db:
    image: "postgres:${POSTGRES_VERSION:-latest}"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - human-essentials
    ports:
      - "5432:5432" # local psql cli
    volumes:
      - postgres:/var/lib/postgresql/data
  selenium:
    profiles:
      - tests
    networks:
      - human-essentials
    # This version should match that of the selenium-webdriver gem (see Gemfile)
    image: selenium/standalone-chrome:latest
    privileged: true
    shm_size: 2g
    environment:
      SE_OPTS: '--enable-managed-downloads true --log-level FINEST'
      SE_NODE_PORT: 5555
      SE_START_XVFB: false
      SE_ENABLE_TRACING: true
    #     SE_JAVA_OPTS: -Dwebdriver.chrome.whitelistedIps=
    #     CHROMEDRIVER_WHITELISTED_IPS: ""
    ports:
      - "4444:4444"
      - "9222:9222"
      - "7900:7900"
#    volumes:
#      - /dev/shm:/dev/shm
  tests:
      profiles:
        - tests
      depends_on:
        - db
        - selenium
      <<: *base-app-settings
      networks:
        - human-essentials
      environment:
        <<: *common-vars
        SELENIUM_HOST: selenium
        RAILS_ENV: test
#        APP_HOST: tests
#      ports:
#        - "3000:3000"
      command: |
        bundle exec rails db:prepare assets:precompile spec:system
      volumes:
        - .:/app

volumes:
  postgres:

networks:
  human-essentials:
#    external: true
    driver: bridge
