version: "3"

x-common-vars: &common-vars
  PG_USERNAME: postgres
  PG_PASSWORD: postgres
  PG_HOST: db
x-base-app-settings: &base-app-settings
  depends_on:
    - db
  image: human-essentials
  environment:
    <<: *common-vars
  networks:
    - human-essentials
  volumes:
    - .:/app

services:
  app:
    profiles:
      - build
    <<: *base-app-settings
    build: .
    command: echo Base image only for building
  web:
    <<: *base-app-settings
    ports:
      - "3000:3000"
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b 0.0.0.0"
  worker:
    <<: *base-app-settings
    command: bundle exec rails jobs:work
  db:
    image: "postgres:${POSTGRES_VERSION:-latest}"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - human-essentials
    ports:
      - "5432:5432" # local psql cli
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

networks:
  human-essentials:
